In [2]:
from tensor import Tensor

In [27]:
# checking grad, direct sigmoid function and manual op sigmoid  funciton
# direct sigmoid function

x = Tensor(2.0)
y = x.sigmoid()
y.backward()
x.grad

0.10499358540350662

In [28]:
# manual sigmoid
x_1 = Tensor(2.0)
y_1 = Tensor(1.0)/(Tensor(1.0)+((-x_1).exp()))
y_1.backward()
x_1.grad


0.1049935854035065

In [23]:
# checking the averageing the loss and manual averaging the grad
# manual grad
w = Tensor(2.0)
x = [Tensor(2.0),Tensor(3.0)]
y = [Tensor(1.0),Tensor(2.0)]
loss = [((w*xi)-yi)**2 for xi,yi in zip(x,y)]
loss[1].backward()
loss[0].backward()
w.grad/2

18.0

In [24]:
# averaging the loss grad
w = Tensor(2.0)
x = [Tensor(2.0),Tensor(3.0)]
y = [Tensor(1.0),Tensor(2.0)]
loss = [((w*xi)-yi)**2 for xi,yi in zip(x,y)]
avg_loss = (loss[0]+loss[1])/2
avg_loss.backward()
w.grad

18.0

Softmax

In [7]:
from nn import Softmax
import numpy as np
from tensor import Tensor

In [10]:
np.random.seed(101)
np_to_tensor = np.vectorize(lambda x: Tensor(x))
x = np.random.randn(5)
a = np_to_tensor(x)
x = np_to_tensor(x)

In [11]:
# nn Softmax
sf  = Softmax()
o = sf(x)
o

[Tensor(0.6540041214179446, grad_fn=<SoftmaxBackward>),
 Tensor(0.08180975761030067, grad_fn=<SoftmaxBackward>),
 Tensor(0.1082272583598544, grad_fn=<SoftmaxBackward>),
 Tensor(0.07224691070875887, grad_fn=<SoftmaxBackward>),
 Tensor(0.08371195190314144, grad_fn=<SoftmaxBackward>)]

In [75]:
o[-1].backward()

In [76]:
for xi in x:
    print(xi.grad)

-0.054747961556595254
-0.006848454494281149
-0.009059915046428994
-0.006047929914402177
0.07670426101170758


In [85]:
# manual Softmax
o_1 = np.exp(a)/np.sum(np.exp(a),axis=-1,keepdims=True)
o_1

array([Tensor(0.6540041214179446, grad_fn=<DivBackward>),
       Tensor(0.08180975761030067, grad_fn=<DivBackward>),
       Tensor(0.1082272583598544, grad_fn=<DivBackward>),
       Tensor(0.07224691070875887, grad_fn=<DivBackward>),
       Tensor(0.08371195190314144, grad_fn=<DivBackward>)], dtype=object)

In [78]:
o_1[-1].backward()

In [79]:
for xi in x:
    print(xi.grad)

-0.054747961556595254
-0.006848454494281149
-0.009059915046428994
-0.006047929914402177
0.07670426101170758


In [86]:
# grad of all variable
for xi in x:
    xi.backward()

for xi in x:
    print(xi.grad)

1.0
1.0
1.0
1.0
1.0


In [87]:
for ai in a:
    ai.backward()

for ai in a:
    print(ai.grad)

1.0
1.0
1.0
1.0
1.0


In [1]:
import torch

In [2]:
torch.manual_seed(101)
z = torch.randn(5,requires_grad=True)

In [3]:
z

tensor([-1.3905, -0.8152, -0.3204,  0.7377, -1.7534], requires_grad=True)

In [4]:
sft = torch.nn.Softmax()

In [5]:
o_2 = sft(z)
print(o_2)

tensor([0.0676, 0.1202, 0.1971, 0.5680, 0.0470], grad_fn=<SoftmaxBackward0>)


C:\Users\Jung__tek\AppData\Local\Temp\ipykernel_4000\744034382.py:1: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  o_2 = sft(z)


In [ ]:
o_2[1].backward()
z.grad

tensor([-0.0081,  0.1058, -0.0237, -0.0683, -0.0057])

In [19]:
z = [Tensor(-1.3905), Tensor(-0.8152), Tensor(-0.3204),  Tensor(0.7377), Tensor(-1.7534)]
o3 = sf(z)

In [20]:
o3[1].backward()
for zi in z:
    print(zi.grad)

-0.008128083943991338
0.1057549937586445
-0.023698819067821158
-0.06827374041828776
-0.0056543503285442385
