In [7]:
import numpy as np
from tensor import Tensor
from nn import Sigmoid,LSTM

In [8]:
# LSTM Implementation
k = 1/4
bound = np.sqrt(k)
hidden_size =4
input_size = 2

In [9]:
random_wf = np.random.uniform(-bound,bound,(hidden_size,hidden_size))
random_uf = np.random.uniform(-bound,bound,(hidden_size,input_size))
random_bf = np.random.uniform(-bound,bound,size=(hidden_size))

In [10]:
x = np.random.randn(3,2)
h = np.random.randn(4)

In [11]:
f = np.dot(random_uf,x[0]) + np.dot(random_wf,h)+random_bf

In [6]:
sigmoid = Sigmoid()

In [9]:
f*f

array([1.28189369e-01, 1.90469072e+00, 5.04960786e-02, 1.85029887e-03])

In [ ]:
sigmoid(f) # 

array([Tensor(0.4114352159642986, grad_fn=<SigmoidBackward>),
       Tensor(0.7990079159547252, grad_fn=<SigmoidBackward>),
       Tensor(0.4440568797887326, grad_fn=<SigmoidBackward>),
       Tensor(0.48924788272490993, grad_fn=<SigmoidBackward>)],
      dtype=object)

In [9]:
lstm = LSTM(2,4)

In [10]:
output,h,s = lstm.forward(x)

In [11]:
s

array([Tensor(0.8832316691201477, grad_fn=<AddBackward>),
       Tensor(0.37598507400950737, grad_fn=<AddBackward>),
       Tensor(0.5081084425584506, grad_fn=<AddBackward>),
       Tensor(0.5162766265663502, grad_fn=<AddBackward>)], dtype=object)

In [13]:
len(lstm.parameters())

112

In [14]:
(4*4+4*2+4)*4

112

In [12]:
# GRU
from nn import GRU

In [13]:
gru= GRU(2,4)

In [15]:
output,h=gru.forward(x)

In [ ]:
s

array([Tensor(0.5035130039846237, grad_fn=<AddBackward>),
       Tensor(0.526806632013153, grad_fn=<AddBackward>),
       Tensor(0.23293936475373767, grad_fn=<AddBackward>),
       Tensor(0.40876695886780007, grad_fn=<AddBackward>)], dtype=object)

In [14]:
Tensor(1)-s

TypeError: unsupported operand type(s) for +: 'int' and 'Tensor'

In [16]:
a = np.random.randn(4)

In [17]:
a

array([ 1.44984457, -1.12311203,  0.27402535,  0.30952411])

In [18]:
1-a

array([-0.44984457,  2.12311203,  0.72597465,  0.69047589])

In [20]:
Tensor(1)-s[0]

Tensor(0.49648699601537627, grad_fn=<SubBackward>)

In [26]:
-s+Tensor(1)

array([Tensor(0.49648699601537627, grad_fn=<AddBackward>),
       Tensor(0.47319336798684697, grad_fn=<AddBackward>),
       Tensor(0.7670606352462623, grad_fn=<AddBackward>),
       Tensor(0.5912330411322, grad_fn=<AddBackward>)], dtype=object)

In [27]:
s

array([Tensor(0.5035130039846237, grad_fn=<AddBackward>),
       Tensor(0.526806632013153, grad_fn=<AddBackward>),
       Tensor(0.23293936475373767, grad_fn=<AddBackward>),
       Tensor(0.40876695886780007, grad_fn=<AddBackward>)], dtype=object)

In [16]:
-h

array([Tensor(-0.4222678966583345, grad_fn=<NegBackward>),
       Tensor(-0.4816583691124943, grad_fn=<NegBackward>),
       Tensor(-0.4006081370934891, grad_fn=<NegBackward>),
       Tensor(-0.5540443739887331, grad_fn=<NegBackward>)], dtype=object)

In [17]:
h

array([Tensor(0.4222678966583345, grad_fn=<AddBackward>),
       Tensor(0.4816583691124943, grad_fn=<AddBackward>),
       Tensor(0.4006081370934891, grad_fn=<AddBackward>),
       Tensor(0.5540443739887331, grad_fn=<AddBackward>)], dtype=object)