In [1]:
import numpy as np

In [3]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.exp(np.arange(0,8,2,dtype=float))

array([  1.        ,   7.3890561 ,  54.59815003, 403.42879349])

In [7]:
import math

In [8]:
np.exp(np.arange(0,4,2,dtype=float)*(-math.log(10000.0)/4))

array([1.  , 0.01])

In [11]:
pe = np.zeros((3,4))

In [13]:
pe[:,0::2],pe[:,1::2]

(array([[0., 0.],
        [0., 0.],
        [0., 0.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [2]:
from nn import PositionalEcnoding,MultiHeadAttention

In [3]:
pe = PositionalEcnoding(4,3)

In [7]:
x = np.random.randn(3,4)

In [8]:
x

array([[ 0.98715121, -0.23711054, -0.52197548, -1.0151971 ],
       [-0.40349247,  0.44291966, -0.7079462 , -1.26090474],
       [ 1.61697593,  0.44286343, -0.65353503,  0.37747418]])

In [13]:
pos_enc = pe(x)

In [15]:
type(pos_enc)

numpy.ndarray

In [5]:
512//8

64

In [21]:
x = np.random.randn(4,512)
y =np.random.randn(4,4)

In [23]:
wq = np.random.randn(512,512)
wqh1 =np.dot(x[:,0:64],wq[0:64,:])

In [25]:
wqh1.shape

(4, 512)

In [20]:
np.concatenate([x,y]).shape

(8, 4)

In [27]:
a = np.random.randn(4,8)
b = np.random.rand(4,8)
np.concatenate([a,b]).shape

(8, 8)

In [2]:
from tensor import Tensor

In [3]:
a = Tensor(3)

In [4]:
np.sqrt(a)

Tensor(1.7320508075688772, grad_fn=<PowBackward>)

In [5]:
np.sqrt(3)

1.7320508075688772

In [6]:
q = np.random.randn(2,4,3)

In [7]:
scores = np.matmul(q,q.transpose(0,2,1)) # Q*Kt ; matrix multiplication; shape(head, seq_len,seq_len)
scores/= np.sqrt(2) # scaling by sq-root(dk)

In [1]:
from nn import PositionalEcnoding,MultiHeadAttention
from tensor import Tensor
import numpy as np

In [2]:
mha = MultiHeadAttention(512,8)

In [3]:
x = np.random.randn(4,512)

In [4]:
output = mha.forward(x)

In [5]:
output.shape

(4, 512)

In [6]:
output

array([[Tensor(-4.551335751004077, grad_fn=<AddBackward>),
        Tensor(-2.6722370158827373, grad_fn=<AddBackward>),
        Tensor(-0.02198226154238625, grad_fn=<AddBackward>), ...,
        Tensor(0.34355011937099267, grad_fn=<AddBackward>),
        Tensor(1.8655004365717756, grad_fn=<AddBackward>),
        Tensor(4.118713075538865, grad_fn=<AddBackward>)],
       [Tensor(2.19640913799146, grad_fn=<AddBackward>),
        Tensor(-1.1158302874390875, grad_fn=<AddBackward>),
        Tensor(-7.589483178632664, grad_fn=<AddBackward>), ...,
        Tensor(1.8491020034248338, grad_fn=<AddBackward>),
        Tensor(1.8110812146760036, grad_fn=<AddBackward>),
        Tensor(2.914769411480942, grad_fn=<AddBackward>)],
       [Tensor(-1.8584360422607484, grad_fn=<AddBackward>),
        Tensor(-2.857884032758778, grad_fn=<AddBackward>),
        Tensor(-2.3160478134935603, grad_fn=<AddBackward>), ...,
        Tensor(1.1345201943449346, grad_fn=<AddBackward>),
        Tensor(0.07910310308684734, 

In [12]:
output

array([[Tensor(-121.47617100734381, grad_fn=<AddBackward>),
        Tensor(-72.54502718937418, grad_fn=<AddBackward>),
        Tensor(484.3578411608605, grad_fn=<AddBackward>), ...,
        Tensor(680.6831351938529, grad_fn=<AddBackward>),
        Tensor(-297.7224704964656, grad_fn=<AddBackward>),
        Tensor(527.3931254426542, grad_fn=<AddBackward>)],
       [Tensor(-197.0257904435052, grad_fn=<AddBackward>),
        Tensor(277.1025537510857, grad_fn=<AddBackward>),
        Tensor(-1.1106454393125393, grad_fn=<AddBackward>), ...,
        Tensor(589.1544881625871, grad_fn=<AddBackward>),
        Tensor(-455.7268151811167, grad_fn=<AddBackward>),
        Tensor(-208.18742678846954, grad_fn=<AddBackward>)],
       [Tensor(-746.0902055435926, grad_fn=<AddBackward>),
        Tensor(-19.270534824989582, grad_fn=<AddBackward>),
        Tensor(95.58430353812841, grad_fn=<AddBackward>), ...,
        Tensor(254.9213677350748, grad_fn=<AddBackward>),
        Tensor(-877.5993469242328, grad_fn

In [7]:
a = np.random.randn(4,5)

In [10]:
a

array([[ 0.68789904,  0.91942054,  1.15828316,  1.93715782,  0.64008033],
       [ 1.71451435,  1.06411496, -0.71832199,  1.15125104,  0.15252911],
       [ 0.19901719, -0.81865864, -1.03042105,  0.29804491,  0.11320987],
       [ 0.85204124, -0.88845876, -2.19101534, -0.32647699, -0.01543775]])

In [9]:
np.exp(a)

array([[1.98953121, 2.50783679, 3.18446137, 6.93900106, 1.89663323],
       [5.55397758, 2.89827275, 0.48756972, 3.16214642, 1.16477637],
       [1.22020294, 0.44102283, 0.35685667, 1.34722229, 1.11986693],
       [2.34442751, 0.41128916, 0.11180317, 0.72146097, 0.98468081]])

In [15]:
np.exp(a)/np.sum(np.exp(a),axis=-1,keepdims=True)

array([[0.12045016, 0.15182941, 0.19279361, 0.42010088, 0.11482594],
       [0.41863912, 0.21846152, 0.03675128, 0.23835138, 0.08779671],
       [0.27205267, 0.09832909, 0.07956366, 0.30037251, 0.24968207],
       [0.51259313, 0.08992558, 0.024445  , 0.15774253, 0.21529376]])

ADD Normalization and FFN

In [1]:
from nn import MultiHeadAttention, LayerNorm, Softmax,Relu,LinearLayer,TransformerEncoderLayer,PositionalEcnoding,Embedding
from tensor import Tensor
import numpy as np

In [2]:
x = np.random.randn(3,4)
# mha = MultiHeadAttention(4,2)

In [10]:
output = mha(x)

In [11]:
ln = LayerNorm(4,act=None)

In [12]:
output

array([[Tensor(-6.639741243699108, grad_fn=<AddBackward>),
        Tensor(2.360919585478614, grad_fn=<AddBackward>),
        Tensor(-5.230112761700893, grad_fn=<AddBackward>),
        Tensor(1.387294598025599, grad_fn=<AddBackward>)],
       [Tensor(-6.633134762929001, grad_fn=<AddBackward>),
        Tensor(4.883356826969166, grad_fn=<AddBackward>),
        Tensor(-4.838258123784768, grad_fn=<AddBackward>),
        Tensor(1.0706922009131499, grad_fn=<AddBackward>)],
       [Tensor(3.0044524999981412, grad_fn=<AddBackward>),
        Tensor(-1.9357024195057084, grad_fn=<AddBackward>),
        Tensor(3.0998128129443865, grad_fn=<AddBackward>),
        Tensor(-0.5540989580828817, grad_fn=<AddBackward>)]], dtype=object)

In [13]:
ln(output[0].tolist())

[Tensor(-1.1665590598767572, grad_fn=<AddBackward>),
 Tensor(1.1113857825730686, grad_fn=<AddBackward>),
 Tensor(-0.8098012627238158, grad_fn=<AddBackward>),
 Tensor(0.8649745400275043, grad_fn=<AddBackward>)]

In [18]:
output_ln = ln(output)

In [15]:
output

array([[Tensor(-6.639741243699108, grad_fn=<AddBackward>),
        Tensor(2.360919585478614, grad_fn=<AddBackward>),
        Tensor(-5.230112761700893, grad_fn=<AddBackward>),
        Tensor(1.387294598025599, grad_fn=<AddBackward>)],
       [Tensor(-6.633134762929001, grad_fn=<AddBackward>),
        Tensor(4.883356826969166, grad_fn=<AddBackward>),
        Tensor(-4.838258123784768, grad_fn=<AddBackward>),
        Tensor(1.0706922009131499, grad_fn=<AddBackward>)],
       [Tensor(3.0044524999981412, grad_fn=<AddBackward>),
        Tensor(-1.9357024195057084, grad_fn=<AddBackward>),
        Tensor(3.0998128129443865, grad_fn=<AddBackward>),
        Tensor(-0.5540989580828817, grad_fn=<AddBackward>)]], dtype=object)

In [20]:
output_ln+x

array([[Tensor(-0.6241218977941035, grad_fn=<AddBackward>),
        Tensor(0.8499676548567123, grad_fn=<AddBackward>),
        Tensor(-1.2313042868810053, grad_fn=<AddBackward>),
        Tensor(0.6418611223736536, grad_fn=<AddBackward>)],
       [Tensor(-1.854375730141487, grad_fn=<AddBackward>),
        Tensor(1.0923442754701005, grad_fn=<AddBackward>),
        Tensor(-1.6939014687488836, grad_fn=<AddBackward>),
        Tensor(1.2367386896545969, grad_fn=<AddBackward>)],
       [Tensor(2.3637562886140104, grad_fn=<AddBackward>),
        Tensor(-1.0569459623489605, grad_fn=<AddBackward>),
        Tensor(2.0247855394001557, grad_fn=<AddBackward>),
        Tensor(-0.2500291772068677, grad_fn=<AddBackward>)]], dtype=object)

In [8]:
ln = LinearLayer(4,4)

In [9]:
out = [ln(xi) for xi in x]

In [10]:
out+x

array([[Tensor(1.6446586087927701, grad_fn=<AddBackward>),
        Tensor(1.6305453804099206, grad_fn=<AddBackward>),
        Tensor(1.2755924291056868, grad_fn=<AddBackward>),
        Tensor(1.49230319932944, grad_fn=<AddBackward>)],
       [Tensor(-1.2465333626014412, grad_fn=<AddBackward>),
        Tensor(1.3980338252794386, grad_fn=<AddBackward>),
        Tensor(2.625910823186821, grad_fn=<AddBackward>),
        Tensor(0.05887795328954864, grad_fn=<AddBackward>)],
       [Tensor(1.2001019776724011, grad_fn=<AddBackward>),
        Tensor(0.7442702496188318, grad_fn=<AddBackward>),
        Tensor(0.5182045113132802, grad_fn=<AddBackward>),
        Tensor(1.3955641985354235, grad_fn=<AddBackward>)]], dtype=object)

In [11]:
x

array([[ 0.66708297,  0.78642836, -0.20732489,  0.03921109],
       [-1.24653336, -0.13374642,  2.62591082,  0.05887795],
       [-0.10489723, -0.26330771, -0.50555724,  0.26270129]])

In [12]:
out

[[Tensor(0.9775756423884646, grad_fn=<ReluBackward>),
  Tensor(0.8441170167371177, grad_fn=<ReluBackward>),
  Tensor(1.482917315645065, grad_fn=<ReluBackward>),
  Tensor(1.4530921102108405, grad_fn=<ReluBackward>)],
 [Tensor(0, grad_fn=<ReluBackward>),
  Tensor(1.5317802462155414, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>)],
 [Tensor(1.3049992068594234, grad_fn=<ReluBackward>),
  Tensor(1.0075779587615603, grad_fn=<ReluBackward>),
  Tensor(1.0237617481455064, grad_fn=<ReluBackward>),
  Tensor(1.132862913499222, grad_fn=<ReluBackward>)]]

In [2]:
# Decoder Layer
te = TransformerEncoderLayer(3,4,10,10,2)

In [3]:
x = np.random.randint(0,10,3)

In [4]:
te(x)

[[Tensor(0.042036396883195215, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.6689858510297543, grad_fn=<ReluBackward>),
  Tensor(0.9285730042932256, grad_fn=<ReluBackward>)],
 [Tensor(1.5099264487888564, grad_fn=<ReluBackward>),
  Tensor(0.20325874784064285, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>)],
 [Tensor(0.10558420042598311, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(1.0722236472782538, grad_fn=<ReluBackward>),
  Tensor(0.44680784893882153, grad_fn=<ReluBackward>)]]

In [10]:
ie = Embedding(10,4)
pe = PositionalEcnoding(3,4)
mha = MultiHeadAttention(4,2)
ln = LayerNorm(4)

In [11]:
out = ie(x)
out = out+pe()
out = mha(out)+out

In [12]:
out

array([[Tensor(-2.511855338905789, grad_fn=<AddBackward>),
        Tensor(1.6884963169134553, grad_fn=<AddBackward>),
        Tensor(3.2800727896593993, grad_fn=<AddBackward>),
        Tensor(1.7993749872592706, grad_fn=<AddBackward>)],
       [Tensor(1.1772749786683638, grad_fn=<AddBackward>),
        Tensor(3.575119800482314, grad_fn=<AddBackward>),
        Tensor(2.8363396482406897, grad_fn=<AddBackward>),
        Tensor(2.159051750683578, grad_fn=<AddBackward>)],
       [Tensor(-5.036166062798037, grad_fn=<AddBackward>),
        Tensor(0.3798492038061809, grad_fn=<AddBackward>),
        Tensor(4.003182570522754, grad_fn=<AddBackward>),
        Tensor(3.57874550663643, grad_fn=<AddBackward>)]], dtype=object)

In [13]:
mha(out)

array([[Tensor(-5.261980408410567, grad_fn=<AddBackward>),
        Tensor(5.8174097233099005, grad_fn=<AddBackward>),
        Tensor(11.651601439452856, grad_fn=<AddBackward>),
        Tensor(4.576987990168175, grad_fn=<AddBackward>)],
       [Tensor(-5.260522512859529, grad_fn=<AddBackward>),
        Tensor(5.81929885893952, grad_fn=<AddBackward>),
        Tensor(11.652140930128386, grad_fn=<AddBackward>),
        Tensor(4.57781951050289, grad_fn=<AddBackward>)],
       [Tensor(-5.259543903912284, grad_fn=<AddBackward>),
        Tensor(5.820546528643176, grad_fn=<AddBackward>),
        Tensor(11.652538451034822, grad_fn=<AddBackward>),
        Tensor(4.578406359094784, grad_fn=<AddBackward>)]], dtype=object)

In [25]:
out.dtype=='O'

True