In [1]:
import numpy as np
from nn import MultiHeadAttention,Tensor

In [6]:
mask = np.triu(np.ones((2,4,4)),k=1).astype(bool)

In [7]:
scores = np.random.randn(2,4,4)

In [8]:
# masked softmax
masked_scores = np.where(mask,-np.inf,scores)
# masked_scores = np_to_tensor(masked_scores)

In [9]:
masked_scores

array([[[ 0.32102265,        -inf,        -inf,        -inf],
        [-1.29609073,  0.57627982,        -inf,        -inf],
        [ 0.43666993,  0.53661296,  0.52455076,        -inf],
        [-1.51216444, -0.70759317, -2.4941274 ,  1.6476766 ]],

       [[-0.60071008,        -inf,        -inf,        -inf],
        [-0.76468462, -1.66865086,        -inf,        -inf],
        [ 0.28072426,  0.61694707, -1.28246518,        -inf],
        [-0.32544925,  0.01721633, -0.12058431, -0.0762829 ]]])

In [10]:
exp_scores = np.exp(masked_scores)
scores_sm = exp_scores/np.sum(exp_scores,axis=-1,keepdims=True)

In [11]:
scores_sm

array([[[1.        , 0.        , 0.        , 0.        ],
        [0.13326767, 0.86673233, 0.        , 0.        ],
        [0.31279657, 0.34567398, 0.34152944, 0.        ],
        [0.0367956 , 0.08226531, 0.01378272, 0.86715637]],

       [[1.        , 0.        , 0.        , 0.        ],
        [0.71176388, 0.28823612, 0.        , 0.        ],
        [0.38327131, 0.53644602, 0.08028266, 0.        ],
        [0.20329284, 0.28637814, 0.24951336, 0.26081566]]])

In [12]:
exp_scores

array([[[1.3785368 , 0.        , 0.        , 0.        ],
        [0.27359928, 1.77940639, 0.        , 0.        ],
        [1.54754519, 1.71020451, 1.6896996 , 0.        ],
        [0.22043235, 0.49282893, 0.08256847, 5.19489595]],

       [[0.54842207, 0.        , 0.        , 0.        ],
        [0.46548071, 0.18850121, 0.        , 0.        ],
        [1.32408844, 1.85326152, 0.27735273, 0.        ],
        [0.72220283, 1.01736539, 0.88640235, 0.92655404]]])

In [2]:
# testing
decoder_mha = MultiHeadAttention(4,2,mask=True)

In [3]:
x = np.random.randn(6,4)

In [5]:
decoder_mha(x)

[[[Tensor(-3.594760063820764, grad_fn=<DivBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)]
  [Tensor(-2.0701753840146466, grad_fn=<DivBackward>)
   Tensor(2.470386170734479, grad_fn=<DivBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)]
  [Tensor(1.7872874795944111, grad_fn=<DivBackward>)
   Tensor(-2.0324908692594295, grad_fn=<DivBackward>)
   Tensor(1.2830104683851236, grad_fn=<DivBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)
   Tensor(-inf, grad_fn=<NoneBackward>)]
  [Tensor(4.070759741517536, grad_fn=<DivBackward>)
   Tensor(-5.39935965041701, grad_fn=<DivBackward>)
   Tensor(3.606375037333029, grad_fn=<DivBackward>)
   Tensor(2.9817735689259575, grad_fn=<Div

array([[Tensor(9.6990377657093, grad_fn=<AddBackward>),
        Tensor(1.0509971543400365, grad_fn=<AddBackward>),
        Tensor(1.0960242223439352, grad_fn=<AddBackward>),
        Tensor(7.01108541195989, grad_fn=<AddBackward>)],
       [Tensor(0.6352129967910511, grad_fn=<AddBackward>),
        Tensor(5.469397956723299, grad_fn=<AddBackward>),
        Tensor(7.619279938180826, grad_fn=<AddBackward>),
        Tensor(2.070880781803244, grad_fn=<AddBackward>)],
       [Tensor(3.97102074244293, grad_fn=<AddBackward>),
        Tensor(-3.480563541419489, grad_fn=<AddBackward>),
        Tensor(-0.5216194490724876, grad_fn=<AddBackward>),
        Tensor(3.221859088241157, grad_fn=<AddBackward>)],
       [Tensor(3.1288355539247235, grad_fn=<AddBackward>),
        Tensor(-3.0139615108611166, grad_fn=<AddBackward>),
        Tensor(-1.8392521042237067, grad_fn=<AddBackward>),
        Tensor(2.121928643938757, grad_fn=<AddBackward>)],
       [Tensor(-0.6152546726178196, grad_fn=<AddBackward>),
 

In [15]:
x = np.random.randn(4,4)

In [18]:
np.exp(x)/np.sum(np.exp(x),axis=-1,keepdims=True)

array([[0.09339752, 0.23805229, 0.52417333, 0.14437686],
       [0.04920652, 0.53397228, 0.11097922, 0.30584198],
       [0.23755683, 0.12931227, 0.3262771 , 0.3068538 ],
       [0.35153752, 0.19493892, 0.32379323, 0.12973033]])

In [1]:
# Decoder layer
from nn import MultiHeadAttention, LayerNorm, Softmax,Relu,LinearLayer,TransformerDecoderLayer,PositionalEcnoding,Embedding
from tensor import Tensor
import numpy as np

In [2]:
td= TransformerDecoderLayer(3,4,10,10,2)

In [3]:
x = np.random.randint(0,10,3)
q = np.random.randn(3,4)
k = np.random.randn(3,4)

In [4]:
x

array([8, 5, 6])

In [5]:
td(q,k,x)

[[Tensor(0.4277948944569567, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.039597083924540206, grad_fn=<ReluBackward>),
  Tensor(1.1275812310939748, grad_fn=<ReluBackward>)],
 [Tensor(1.1493073866768604, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.81259109607819, grad_fn=<ReluBackward>)],
 [Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.6546298739672148, grad_fn=<ReluBackward>),
  Tensor(1.088147924939086, grad_fn=<ReluBackward>)]]

In [2]:
ie = Embedding(10,4)
pe = PositionalEcnoding(3,4)
mha = MultiHeadAttention(4,2)
ln = LayerNorm(4)
mask_mha = MultiHeadAttention(4,2,mask=True)

In [3]:
x = np.random.randint(0,10,3)

In [ ]:
out = ie(x)
out = out + pe()
out = ln(out+mask_mha(out,out,out))
out = np.array(out) # layernorm return list so,
out = ln(out+ mha(out,out,out))


In [15]:
out

[[Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.3526634059732605, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(1.416311507296194, grad_fn=<ReluBackward>)],
 [Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.29857490111460444, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(1.4927553224150554, grad_fn=<ReluBackward>)],
 [Tensor(0, grad_fn=<ReluBackward>),
  Tensor(0.7242165665555933, grad_fn=<ReluBackward>),
  Tensor(0, grad_fn=<ReluBackward>),
  Tensor(1.2259731625781805, grad_fn=<ReluBackward>)]]